apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry
spec:
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      labels:
        app: private-registry
    spec:
      containers:
      - name: private-registry
        image: registry:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: private-registry-svc
spec:
  selector:
    app: private-registry
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer

