apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-web
spec:
  selector:
    matchLabels:
      app: myapp-web
  template:
    metadata:
      labels:
        app: myapp-web
    spec:
      containers:
      - name: myapp-web
        image: 10.96.229.28:5000/nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
