apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-web
spec:
  selector:
    matchLabels:
      app: myapp-web
  template:
    metadata:
      labels:
        app: myapp-web
    spec:
      containers:
      - name: myapp-web
        image: 10.104.73.82:5000/nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: myapp-web-svc
spec:
  selector:
    app: myapp-web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

